backend:
  name: github
  repo: dillionmegida/dillionmegida.com
media_folder: "static/img/uploads"
public_folder: "img/uploads"
collections:
  - name: "blogs"
    label: "Blogs"
    description: "Blog posts"
    folder: "src/pages/p"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date }
      - { name: pageDescription, label: Excerpt / Page Description }
      - { name: pageKeywords, label: SEO Keywords }
      - { name: tags, label: Blog Tags, widget: list, required: false }
      - { name: cover, label: Blog Cover Link, required: false }
      - { name: body, label: Body, widget: markdown }
  - name: "contents"
    label: "Contents"
    description: "All my contents"
    files:
      - label: "Youtube Videos"
        name: "youtube"
        file: "data/contents/youtube.yml"
        format: 'yml'
        create: true
        fields:
          - { name: content.title, label: Title }
          - { name: content.link, label: Link }
          - { name: content.tags, label: Content tags, widget: list, required: false }

publish_mode: editorial_workflow
